// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acirnxftgkolszfqpddk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjaXJueGZ0Z2tvbHN6ZnFwZGRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDc1NTYsImV4cCI6MjA2NjE4MzU1Nn0.N-Nmhh7wvzRX4cP8Pu6Q1p8tv4gysbULEBhiZlqjc-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);